"""Regenerate the two task-board files from one source of truth.

Run from the repo root:  python docs/research/build_board.py

Edit `docs/research/task_board_source.json` (tasks, workstreams, the `done`
list) and re-run. Never hand-edit docs/STAGE2_TASK_BOARD.md or
docs/task_board.html: both are generated and your edit will be overwritten.
"""

from __future__ import annotations

import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = ROOT / "docs" / "research" / "task_board_source.json"
TEMPLATE = ROOT / "docs" / "research" / "task_board_template.html"
OUT_MD = ROOT / "docs" / "STAGE2_TASK_BOARD.md"
OUT_HTML = ROOT / "docs" / "task_board.html"

ROLE_LABEL = {"dev": "Dev", "designer": "Designer", "team": "Team"}

RULES = [
    "**No demographics in any score path.** School type, region, language label, income proxy, name, fluency and timing features live only in the protected-attributes table for audits.",
    "**Every level decomposes into verified quotes.** A quote that is not a literal substring of the source is dropped. \"No evidence\" is a state, never \"weak\".",
    "**One candidate per model call, absolute rubric.** Never ask the model to compare or rank two people. Ranking is computed from levels.",
    "**Competencies 8 and 9 (purpose-driven, wounded leadership) get flags, never an AI level.** The form never asks about trauma.",
    "**Weights, cut-offs, bands are the client's.** Displayed as \"owned by inVision U / Talent Craft\", versioned, signed. Overrides append, never overwrite.",
    "**Nothing candidate-facing ships without the leak guard and a committee release gate.** No level names, no test items, no comparisons, competency 9 suppressed.",
    "**Kazakh first.** Rubric in English, candidate text native, strongest model for kk/mixed, written presentation is the canonical input, ASR only for quotes. Never Whisper for Kazakh.",
    "**Demo from cached results.** Anything live on stage has a cached fallback. Scenario Lab is unweighted and labeled \"observed in simulation\".",
]

STOP = [
    "English-only keyword banks and role-name matching",
    "School-advantage table, adversity decrement, growth delta, GPA dimension, length scores",
    "The AI-text \"authenticity score\" and every \"possibly AI-generated\" label",
    "Character-frequency language detection as a gate",
    "Any scoring that depends on a Kazakh ASR transcript; Whisper for Kazakh",
    "Filler ratios, word length, hapax, speech rate, pauses as score inputs",
    "Haiku-class models for Kazakh or mixed text",
    "Fairness audit grouped by recommendation category",
    "Recording \"weak\" when nothing was found; scoring a mock transcript; ranking a failed run as 0",
    "Overwriting an AI score on override",
]


def check_dependencies(data: dict) -> None:
    """A task that depends on an id nobody defines is a typo, not a plan."""
    ids = {t[0] for t in data["tasks"]}
    broken = [(t[0], dep) for t in data["tasks"] for dep in t[8] if dep not in ids]
    if broken:
        raise ValueError(f"unknown dependencies: {broken}")
    unknown_done = set(data.get("done", [])) - ids
    if unknown_done:
        raise ValueError(f"done list names unknown tasks: {sorted(unknown_done)}")


def task_lines(task: list, done: set[str]) -> str:
    task_id, _ws, _ph, role, effort, demo, title, detail, deps, section = task
    box = "x" if task_id in done else " "
    tags = [ROLE_LABEL[role], f"effort {effort}"]
    if demo:
        tags.append("**demo-critical**")
    if section:
        tags.append(section)
    markdown_break = "" if task_id in {"FAIR-12", "FAIR-13", "FAIR-14"} else "  "
    line = f"- [{box}] **{task_id}** — {title}{markdown_break}\n  _{' · '.join(tags)}_"
    if detail:
        line += f"{markdown_break}\n  {detail}"
    if deps:
        line += f"{markdown_break}\n  Depends on: {', '.join(deps)}"
    return line


def build_markdown(data: dict) -> str:
    done = set(data.get("done", []))
    tasks = data["tasks"]
    out = [
        "# AI Leader ID — Stage 2 Task Board\n",
        "Generated by `docs/research/build_board.py` from `docs/research/task_board_source.json`. "
        "Do not hand-edit: edit the source and re-run. Companion to `STAGE2_IMPROVEMENT_PLAN.md`, "
        "where section references like §5.1 point. Same board interactive: open `docs/task_board.html`.\n",
        "**Team:** two fullstack developers + one designer (UX/UI and graphic). Tasks are grouped by "
        "**workstream**, not by person: either developer takes any `Dev` task; order is decided by the "
        "dependency chain. `Demo-critical` = must be live or cached for Demo Day Oct 1–3.\n",
        "**Dates:** today Sep 20, 2026 · Demo Day Oct 1–3 · Stage 2 Oct 5 – Nov 10 · Final Demo Day Nov 10.\n",
        f"**Progress:** {len(done)} of {len(tasks)} done. {data.get('done_note', '')}\n",
        "**Legend:** `Dev` either developer · `Designer` · `Team` everyone · effort S = 1–3 days, M = 4–10, L = more\n",
        "## Workstreams at a glance\n",
        "| Stream | Delivers | Tasks | Done | Demo-critical |\n|---|---|---|---|---|",
    ]
    for stream in data["workstreams"]:
        rows = [t for t in tasks if t[1] == stream["id"]]
        out.append(
            f"| **{stream['id']}** {stream['name']} | {stream['blurb']} | {len(rows)} | "
            f"{sum(1 for t in rows if t[0] in done)} | {sum(1 for t in rows if t[5])} |"
        )
    out.append("")

    for stream in data["workstreams"]:
        out.append(f"## {stream['id']} · {stream['name']}\n")
        out.append(f"_{stream['blurb']}_\n")
        for phase in data["phases"]:
            rows = [t for t in tasks if t[1] == stream["id"] and t[2] == phase["id"]]
            if not rows:
                continue
            out.append(f"### {phase['name']} · {phase['when']}\n")
            out.extend(task_lines(t, done) for t in rows)
            out.append("")

    out.append("## Week-by-week index\n")
    for phase in data["phases"]:
        rows = [t for t in tasks if t[2] == phase["id"]]
        for role, label in (("dev", "Developers"), ("designer", "Designer"), ("team", "Team")):
            names = [f"~~{t[0]}~~" if t[0] in done else t[0] for t in rows if t[3] == role]
            if names:
                suffix = "" if any("FAIR-12" in name or "FAIR-14" in name for name in names) else "  "
                out.append(f"**{phase['name']}** {label}: {', '.join(names)}{suffix}")
        out.append("")

    out.append("## Priorities (three-voter Borda ranking, points out of 45)\n")
    for i, (title, why, points, voters) in enumerate(data["priorities"], 1):
        out.append(f"{i}. **{title}** ({points} pts, ranked by {voters}) — {why}")

    out.append("\n## Rules that bind every task\n")
    out.extend(f"- {r}" for r in RULES)
    out.append("\n## Stop doing (delete, don't tune)\n")
    out.extend(f"1. {r}" for r in STOP)
    out.append(
        "\n_Excluded by all reviewers: facial or emotion analysis, voice-stress or fluency scoring, "
        "social-media scraping, third-party reference forms for minors, per-language score calibration, "
        "a rejection-explaining chatbot, rewriting candidate text before scoring._\n"
    )
    return "\n".join(out)


def main() -> None:
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    check_dependencies(data)
    OUT_HTML.write_text(
        TEMPLATE.read_text(encoding="utf-8").replace("__DATA__", json.dumps(data, ensure_ascii=False)),
        encoding="utf-8",
    )
    OUT_MD.write_text(build_markdown(data), encoding="utf-8")
    done = len(data.get("done", []))
    print(f"wrote {OUT_MD.name} and {OUT_HTML.name} — {done}/{len(data['tasks'])} tasks done")


if __name__ == "__main__":
    main()
